<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRtayhql\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRtayhql/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRtayhql.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRtayhql\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRtayhql\appProdProjectContainer([
    'container.build_hash' => 'Rtayhql',
    'container.build_id' => 'c43a0380',
    'container.build_time' => 1731852950,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRtayhql');
