services:
  prestashop:
    container_name: prestashop
    image: karolinaszydelko/wloczki:main
    restart: always
    ports:
      #- 19319:80
      - 19319:443
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_193192
      DB_USER: root
      DB_PASSWD: student
      PS_FOLDER_ADMIN: admin-dev
      PS_FOLDER_INSTALL: install-dev
      PS_DEV_MODE: 1
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:19319
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    networks:
      - be_193192_network
      - admin-mysql_default
    command: >
      /bin/bash -c "
      mysql -u\"$DB_USER\" -p\"$DB_PASSWD\" -h\"$DB_SERVER\" \"$DB_NAME\" < /tmp/sql/dump.sql &&
      mysql -u\"$DB_USER\" -p\"$DB_PASSWD\" -h\"$DB_SERVER\" -e \"UPDATE ps_configuration SET value = '$PS_DOMAIN' WHERE name LIKE '%SHOP_DOMAIN%'\" \"$DB_NAME\" &&
      mysql -u\"$DB_USER\" -p\"$DB_PASSWD\" -h\"$DB_SERVER\" -e \"UPDATE ps_shop_url SET domain = '$PS_DOMAIN', domain_ssl = '$PS_DOMAIN' WHERE id_shop = 1\" \"$DB_NAME\"
      "
    
  caching:
    container_name: caching_service
    image: memcached
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    networks:
      - be_193192_network
       
networks:
    be_193192_network:
    admin-mysql_default:
      external: true