<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerG3hziji\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG3hziji/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerG3hziji.legacy');
=======
if (\class_exists(\ContainerE9fdix4\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE9fdix4/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerE9fdix4.legacy');
>>>>>>> 1284c66d9 (improved css)

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerG3hziji\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerG3hziji\appDevDebugProjectContainer([
    'container.build_hash' => 'G3hziji',
    'container.build_id' => '1a402322',
    'container.build_time' => 1732918964,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG3hziji');
=======
    \class_alias(\ContainerE9fdix4\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerE9fdix4\appDevDebugProjectContainer([
    'container.build_hash' => 'E9fdix4',
    'container.build_id' => 'c71e7bcb',
    'container.build_time' => 1732970472,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE9fdix4');
>>>>>>> 1284c66d9 (improved css)
