<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1hkntis\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1hkntis/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1hkntis.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1hkntis\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container1hkntis\appDevDebugProjectContainer([
    'container.build_hash' => '1hkntis',
    'container.build_id' => '01ff5fec',
    'container.build_time' => 1733226698,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1hkntis');
