<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK1bdznb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK1bdznb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerK1bdznb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerK1bdznb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerK1bdznb\appDevDebugProjectContainer([
    'container.build_hash' => 'K1bdznb',
    'container.build_id' => '42d48a52',
    'container.build_time' => 1735820909,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK1bdznb');
