services:
  mysql:
    container_name: admin-mysql_db
    image: mariadb:11.5.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: BE_193192
    networks:
      - prestashop_network

  prestashop:
    container_name: prestashop
    image: karolinaszydelko/wloczki:main
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
      - 8443:443
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_193192
      DB_USER: root
      DB_PASSWD: student
      PS_FOLDER_ADMIN: admin-dev
      PS_FOLDER_INSTALL: install-dev
      PS_DEV_MODE: 1
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
    volumes:
      - ../prestashop_files:/var/www/html
    networks:
      - prestashop_network
    
  caching:
    container_name: caching_service
    image: memcached
    ports:
      - 11211:11211
    networks:
      - prestashop_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_PORT: 3306
    networks:
      - prestashop_network
       
networks:
    prestashop_network:
